In [1]:
import pandas as pd

In [2]:
import numpy as np

### 1

In [13]:
s=pd.Series(data=['python','java','ruby','pandas'],index=[6,7,8,9])
print(s)
s=s.reindex(index=[9,8,7,6])
print(s)


6    python
7      java
8      ruby
9    pandas
dtype: object
9    pandas
8      ruby
7      java
6    python
dtype: object


### 2.

In [5]:
sample1=pd.Series([2,4,6,8])
sample2=pd.Series([1,3,5,7])
addition=sample1+sample2
subtraction=sample1-sample2
product=sample1*sample2
division=sample1/sample2
print(addition)
print(subtraction)
print(product)
print(division)

0     3
1     7
2    11
3    15
dtype: int64
0    1
1    1
2    1
3    1
dtype: int64
0     2
1    12
2    30
3    56
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
dtype: float64


### 3

In [6]:
sample=pd.Series([1,5,7,9])
type(sample)
print(type(sample))
print(sample.tolist())
print(type(sample.tolist()))


<class 'pandas.core.series.Series'>
[1, 5, 7, 9]
<class 'list'>


### 4

In [7]:
name=['Sachin','Ganguly','Kohli','Johnson','Taylor','Waugh',
'Yuvraj','Kambli','Srinath','Munaf']
score=[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19]
attempts=[1,3,2,3,2,3,1,1,2,1]
qualify=['yes','no','yes','no','no','yes','yes','no','no','yes']
labels=['a','b','c','d','e','f','g','h','i','j']
dataframe={'score':score,'attempts':attempts,'qualify':qualify,
'labels':labels}
examdata=pd.DataFrame(dataframe,index=name)
print(examdata[examdata['score'].isnull()])

         score  attempts qualify labels
Johnson    NaN         3      no      d
Kambli     NaN         1      no      h


### 5

In [8]:
print(pd.datetime.now().date())

2019-12-31


### 6

In [11]:
dd=pd.read_csv('titanic.csv')
result=pd.pivot_table(dd,index=['Sex','Age'],aggfunc=np.sum)
print(result)

                  Fare  Parch  PassengerId  Pclass  SibSp  Survived
Sex    Age                                                         
female 0.75    38.5166      2         1115       6      4         2
       1.00    26.8750      3          555       6      1         2
       2.00   259.4750      9         2278      15      9         2
       3.00    62.6542      3          419       5      4         1
       4.00   114.1417      6         2258      13      4         5
       5.00    90.8708      5         1520      11      7         4
       6.00    64.2750      3         1535       5      4         1
       7.00    26.2500      2          536       2      0         1
       8.00    47.3250      3          263       5      3         1
       9.00   108.7958      7         2178      12     10         0
       10.00   24.1500      2          420       3      0         0
       11.00   31.2750      2          543       3      4         0
       13.00   26.7292      1         1228      

### 7

In [14]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 8

In [15]:
d=np.arange(1,10).reshape(3,3)
print(d.flatten())
print(d.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# 9

In [16]:
t=np.random.random((3,3))
print(t)
print(np.min(t))
print(np.max(t))
print(np.std(t))
print(np.min(t))



[[0.59642396 0.51359009 0.0819883 ]
 [0.91792969 0.59625721 0.69539   ]
 [0.99580848 0.98914295 0.23221512]]
0.08198829929315621
0.9958084816833171
0.3025913645233112
0.08198829929315621


# 10

In [17]:
w=np.random.random((3,3))
r=np.random.random((3,3))
print(np.vstack((w,r)))
print(np.hstack((w,r)))



[[0.69970563 0.38057638 0.94195093]
 [0.32371208 0.57066874 0.02290698]
 [0.91747449 0.76093891 0.60898439]
 [0.05743147 0.30649655 0.22633382]
 [0.46517117 0.47553246 0.34336032]
 [0.7845828  0.83032461 0.71152841]]
[[0.69970563 0.38057638 0.94195093 0.05743147 0.30649655 0.22633382]
 [0.32371208 0.57066874 0.02290698 0.46517117 0.47553246 0.34336032]
 [0.91747449 0.76093891 0.60898439 0.7845828  0.83032461 0.71152841]]
