# Numpy Arrays
## python objects:
1.high-level number objects:integer,floating point
2.containers:lists(costless insertion and append),dictionaries(fast lookup)
## Numpy provides:
1.extension package to Python for multi-dimensional arrays
2.closer to hardware
3.designed for scientific computation
4.Also known as array oriented computing

In [3]:
import numpy as np

In [7]:
ar2=np.array([1,2,3,4])

In [4]:
ar1=np.array([1,4,3,6,7.8])
ar1

array([1. , 4. , 3. , 6. , 7.8])

In [5]:
type(ar1)

numpy.ndarray

In [6]:
ar1.dtype

dtype('float64')

In [9]:
ar2.dtype

dtype('int32')

In [10]:
ar1.ndim

1

In [13]:
d2=np.array([[1,2],[3,4]])
d2

array([[1, 2],
       [3, 4]])

In [15]:
d2.ndim

2

In [16]:
from numpy import array as ar

In [17]:
ar([1,2,3,4])

array([1, 2, 3, 4])

In [19]:
ar3=np.arange(100)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
ar3=np.arange(5,100,5)
ar3

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [22]:
len(ar3)

19

In [23]:
ar3.shape

(19,)

In [24]:
d2.shape

(2, 2)

In [25]:
ar4=np.arange(1,10)
ar4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ar4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
s=np.ones(10)
s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
s.astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
s.astype(str)

array(['1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0'], dtype='<U32')

In [35]:
n=np.arange(1,100)
m=np.arange(100,1,-1)
%timeit n+m

640 ns ± 36.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [36]:
ar5=np.arange(1,10)
ar5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
ar6=np.arange(10,19)
ar6

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [42]:
ar5+ar6

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [43]:
ar5*ar6

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162])

In [44]:
ar5.min()

1

In [45]:
ar6.max()

18

In [46]:
ar5<ar6

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [48]:
ar6[0]

10

In [49]:
ar6[0:5:-1]

array([], dtype=int32)

In [50]:
ar6[ar6>ar5]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [51]:
ar6.mean()

14.0

In [52]:
ar6.argmax()

8

In [53]:
ar6.argmin()

0

In [54]:
ar6

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [55]:
ar6.max()

18

## python objects:
1.high-level number objects:integer,floating point
2.containers:lists(costless insertion and append),dictionaries(fast lookup)
## Numpy provides:
1.extension package to Python for multi-dimensional arrays
2.closer to hardware
3.designed for scientific computation
4.Also known as array oriented computing

In [4]:
a=np.arange(1000)
%timeit a**2

1.55 µs ± 7.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
a1=np.array([[0,1,2,3],[2,4,5,5]])

In [7]:
a1.ndim

2

In [8]:
a1.shape

(2, 4)

In [9]:
a1

array([[0, 1, 2, 3],
       [2, 4, 5, 5]])

In [10]:
a1.reshape(4,2)

array([[0, 1],
       [2, 3],
       [2, 4],
       [5, 5]])

In [11]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [12]:
np.linspace(5,50,5)

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

In [14]:
m=np.linspace(1,100,10)
m

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [15]:
a=[[4,5],[8,7]]
a

[[4, 5], [8, 7]]

In [17]:
a[0][1]

5

In [20]:
np.random.rand(1,9)

array([[0.85466359, 0.68657931, 0.83792133, 0.58554295, 0.88793324,
        0.48530743, 0.74037915, 0.64891374, 0.02053605]])

In [21]:
np.random.rand(5,9)

array([[0.29545213, 0.44763304, 0.63326332, 0.90458932, 0.93290018,
        0.75844736, 0.85802579, 0.24661573, 0.93795863],
       [0.32628332, 0.00689894, 0.44047725, 0.86543642, 0.03902311,
        0.54607103, 0.24650903, 0.5947448 , 0.88941136],
       [0.80768811, 0.32110969, 0.28253837, 0.23954646, 0.72394449,
        0.02410327, 0.67102807, 0.11049796, 0.13417543],
       [0.84011256, 0.39882805, 0.08014946, 0.72002973, 0.52246434,
        0.00678149, 0.64365425, 0.6508156 , 0.96407466],
       [0.81207367, 0.27502844, 0.37353923, 0.60712416, 0.68597427,
        0.12579927, 0.91825187, 0.70584409, 0.76232161]])

In [22]:
np.random.randn(1,9)

array([[ 0.86821941, -0.52532394, -0.55957235, -0.21618785,  0.19405732,
         0.27034297, -0.64386712, -1.90573545,  0.54933236]])

In [24]:
np.random.randint(1,1000)

816

In [26]:
np.random.random_integers(1,50)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  """Entry point for launching an IPython kernel.


18

In [28]:
m=np.random.rand(2,2)
n=np.random.rand(2,2)
print(m)
n

[[0.99901632 0.68815371]
 [0.34415047 0.75799707]]


array([[0.524405  , 0.51850137],
       [0.264017  , 0.42985339]])

In [29]:
np.vstack(n)

array([[0.524405  , 0.51850137],
       [0.264017  , 0.42985339]])

In [30]:
np.vstack((m,n))

array([[0.99901632, 0.68815371],
       [0.34415047, 0.75799707],
       [0.524405  , 0.51850137],
       [0.264017  , 0.42985339]])

In [31]:
np.hstack((m,n))

array([[0.99901632, 0.68815371, 0.524405  , 0.51850137],
       [0.34415047, 0.75799707, 0.264017  , 0.42985339]])

In [32]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3,3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
m=np.diag([6,3,7,8])
m

array([[6, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [37]:
m.diagonal()

array([6, 3, 7, 8])

In [38]:
n.diagonal()

array([0.524405  , 0.42985339])

In [39]:
m.all()

False

In [40]:
m.any()

True

In [41]:
m.argmax(),m.argmin()

(15, 1)

In [42]:
n.argmax()

0

In [43]:
m.max()

8

In [44]:
m.min()

0

In [45]:
m.dtype

dtype('int32')

data types:
b
i
u
f
c
m
M
O
S
U
V

In [48]:
m=np.array([4+2j])
m.dtype

dtype('complex128')

In [52]:
m=np.array([2+3j,4,'python'])
m

array(['(2+3j)', '4', 'python'], dtype='<U64')

In [50]:
m.dtype

dtype('complex128')

In [53]:
m=np.arange(0,4).reshape(2,2)

In [54]:
m

array([[0, 1],
       [2, 3]])

In [61]:
m=np.arange(0,4).reshape(2,2)
m

array([[0, 1],
       [2, 3]])

In [62]:
np.equal(m,n)

array([[False, False],
       [False, False]])

In [70]:
one=np.ones(9,dtype=int).reshape(3,3)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [71]:
five=5*one
five

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [72]:
np.dot(one,five)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [73]:
one*five

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [74]:
one+five

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [76]:
one+five

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [77]:
one[:1,:1]

array([[1]])

In [78]:
one[:2,:2]

array([[1, 1],
       [1, 1]])

In [79]:
one[:3,:3]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [80]:
a2=one[:2,:2]
a2

array([[1, 1],
       [1, 1]])

In [81]:
bol=np.array([[True,False],[True,False]])
bol

array([[ True, False],
       [ True, False]])

In [82]:
a2[bol]

array([1, 1])

In [83]:
d=np.arange(480,555)
d

array([480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492,
       493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531,
       532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544,
       545, 546, 547, 548, 549, 550, 551, 552, 553, 554])

In [85]:
d%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [87]:
d=np.arange(480,555)
a=d%2==0
d[a]

array([480, 482, 484, 486, 488, 490, 492, 494, 496, 498, 500, 502, 504,
       506, 508, 510, 512, 514, 516, 518, 520, 522, 524, 526, 528, 530,
       532, 534, 536, 538, 540, 542, 544, 546, 548, 550, 552, 554])

In [92]:
year=np.arange(1950,2050)
leapyrs=np.logical_or(year%400==0,np.logical_and(year%4==0,year%100!=0) )
year[leapyrs]

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036,
       2040, 2044, 2048])

## repeating  the elements

In [95]:
i=leap.repeat(2)
i

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False,  True,  True,
       False, False,